/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group.oodjAssignment;

import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Saadin
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    fullnameTextField = new javax.swing.JTextField();
    passwordTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    submitButton = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    emailTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Register | AppPay");
    setResizable(false);
    addWindowListener(
      new java.awt.event.WindowAdapter() {
        public void windowClosing(java.awt.event.WindowEvent evt) {
          formWindowClosing(evt);
        }
      }
    );

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    jLabel1.setText("Register Now!");

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jLabel4.setText("Fullname");

    fullnameTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    passwordTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jLabel5.setText("Password");

    submitButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    submitButton.setText("Submit");
    submitButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          submitButtonActionPerformed(evt);
        }
      }
    );

    jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jLabel6.setText("Emaill");

    emailTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(120, 120, 120)
            .addComponent(jLabel1)
            .addContainerGap(120, Short.MAX_VALUE)
        )
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      emailTextField,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      250,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      passwordTextField,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      250,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED
                    )
                    .addComponent(
                      fullnameTextField,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      250,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addComponent(
                  submitButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  100,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(37, 37, 37)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(
                  fullnameTextField,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(
                  emailTextField,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  passwordTextField,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(submitButton)
            .addContainerGap(31, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

    private boolean validateData() {
        String fullname = fullnameTextField.getText();
        String email = emailTextField.getText();
        String password = passwordTextField.getText();

        if (fullname.isEmpty() || email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please Fill All Fields!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        if (!fullname.matches("^[a-zA-Z -]+$")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Invalid Fullname!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        if (!email.matches("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Invalid Email Address!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        if (password.length() < 5) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Password must be at least 5 characters long!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return false;
        }

        return true;
    }

  private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
      if (!validateData()) {
          return;
      }

      try {
          java.io.File file = new java.io.File("credientials.txt");
          if (!file.exists()) {
              file.createNewFile();
          }

          java.io.BufferedReader br = new java.io.BufferedReader(
                  new java.io.FileReader(file)
          );

          String line;
          while ((line = br.readLine()) != null) {
              if (line.equals(fullnameTextField.getText())) {
                  javax.swing.JOptionPane.showMessageDialog(
                          this,
                          "User Already Exists!",
                          "Error",
                          javax.swing.JOptionPane.ERROR_MESSAGE
                  );
                  return;
              }
              br.readLine();
              br.readLine();
              br.readLine();
          }
          br.close();

          java.io.FileWriter fw = new java.io.FileWriter(file, true);
          fw.write(emailTextField.getText() + "\n");
          fw.write(passwordTextField.getText() + "\n");
          fw.write("customer\n");
          fw.write(fullnameTextField.getText() + "\n");
          fw.close();

          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "User Registered Successfully!",
                  "Success",
                  javax.swing.JOptionPane.INFORMATION_MESSAGE
          );

          dispose();
          new LoginForm().setVisible(true);
      } catch (java.io.IOException e) {
          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  e.getMessage(),
                  "Error",
                  javax.swing.JOptionPane.ERROR_MESSAGE
          );
      }
  }//GEN-LAST:event_submitButtonActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      WelcomeForm.getInstance().setVisible(true);
      dispose();
  }//GEN-LAST:event_formWindowClosing

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField emailTextField;
  private javax.swing.JTextField fullnameTextField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField passwordTextField;
  private javax.swing.JButton submitButton;
  // End of variables declaration//GEN-END:variables
}
